# Generated by Django 4.2.17 on 2025-05-29 10:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='ИНН')),
                ('balance', models.PositiveBigIntegerField(default=0, verbose_name='Баланс')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(verbose_name='Сумма')),
                ('payer_inn', models.CharField(max_length=20, verbose_name='ИНН плательщика')),
                ('document_number', models.CharField(max_length=20, verbose_name='Номер документа')),
                ('document_date', models.DateField(verbose_name='Дата документа')),
            ],
        ),
    ]
